apiVersion: v1
kind: Service
metadata:
  name: online-store-service
spec:
  type: NodePort
  selector:
    app: online-store
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-store-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-store
  template:
    metadata:
      labels:
        app: online-store
    spec:
      containers:
        - name: online-store
          image: online-store:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: online-store-config
                  key: APP_PORT
